import React from 'react';
import ReactMarkdown from 'react-markdown';
import { ShieldCheck, Download, RefreshCw } from 'lucide-react';

interface ReportDisplayProps {
  markdown: string;
  onReset: () => void;
}

export const ReportDisplay: React.FC<ReportDisplayProps> = ({ markdown, onReset }) => {
  return (
    <div className="bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden">
      <div className="bg-slate-900 text-white p-6 flex justify-between items-center">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-green-500/20 rounded-lg">
            <ShieldCheck className="text-green-400" size={24} />
          </div>
          <div>
            <h2 className="text-xl font-bold">Tactical Safety Analysis</h2>
            <p className="text-slate-400 text-sm">Generated by FireSmart AI</p>
          </div>
        </div>
        <div className="flex gap-2">
            <button 
                onClick={onReset}
                className="p-2 hover:bg-white/10 rounded-lg transition-colors text-slate-300 hover:text-white"
                title="New Analysis"
            >
                <RefreshCw size={20} />
            </button>
        </div>
      </div>
      
      <div className="p-8 prose prose-slate max-w-none prose-headings:font-bold prose-h2:text-slate-800 prose-h2:border-b prose-h2:border-slate-200 prose-h2:pb-2 prose-h2:mt-8 prose-strong:text-slate-900 prose-table:border prose-th:bg-slate-50 prose-th:p-3 prose-td:p-3">
        <ReactMarkdown>{markdown}</ReactMarkdown>
      </div>

      <div className="bg-slate-50 p-4 border-t border-slate-200 text-center">
        <p className="text-xs text-slate-500">
          Disclaimer: This report is AI-generated for informational purposes only. Always consult with a certified Fire Protection Engineer (FPE) for official compliance.
        </p>
      </div>
    </div>
  );
};